In [2]:
import numpy as np
import pandas as pd

In [172]:
# Make dataframe for coils
coil_names = 'A B'
coil_attr = 'Current Width X Y Z Theta Phi'
coil_a = [93.,.075818,0.,0.,-.359747,0.,0.]
coil_b = [93.,.075818,0.,0.,.359747,0.,0.]
coil_df = pd.DataFrame([coil_a,coil_b],index=coil_names.split(),columns=coil_attr.split())
coil_df.index.name = 'Coil'
coil_df.to_csv('CoilData.csv')
coil_df

      Current   Width    X    Y         Z  Theta  Phi
Coil
A        93.0  7.5818  0.0  0.0 -0.359747    0.0  0.0
B        93.0  7.5818  0.0  0.0  0.359747    0.0  0.0

In [173]:
# Make dataframe for subcoils
coil_hier1 = 'A A A B B B'.split()
coil_hier2 = [1,2,3,1,2,3]
subcoil_index = list(zip(coil_hier1,coil_hier2))
subcoil_index = pd.MultiIndex.from_tuples(subcoil_index)
subcoil_columns = ["Inner Radius","Outer Radius","Coil Turns","Nrho","Nz"]
sc_a1 = [.203517,.215011,1995.9,8,52]
sc_a2 = [.215011,.234632,5150.,8,32]
sc_a3 = [.234632,.255224,5489.5,8,32]
sc_b1 = [.203492,.214731,1976.,8,52]
sc_b2 = [.214732,.234709,5110.,8,32]
sc_b3 = [.234709,.256222,5486.7,8,32]
subcoil_df = pd.DataFrame([sc_a1,sc_a2,sc_a3,sc_b1,sc_b2,sc_b3],index=subcoil_index,columns=subcoil_columns)
subcoil_df.index.names = ['Coil','Subcoil']
subcoil_df.to_csv('SubcoilData.csv')
subcoil_df

              Inner Radius  Outer Radius  Coil Turns  Nrho  Nz
Coil Subcoil
A    1            0.203517      0.215011      1995.9     8  52
     2            0.215011      0.234632      5150.0     8  32
     3            0.234632      0.255224      5489.5     8  32
B    1            0.203492      0.214731      1976.0     8  52
     2            0.214732      0.234709      5110.0     8  32
     3            0.234709      0.256222      5486.7     8  32